### ISSUE TITLE
Algorithm

### ISSUE THREAD

**Issue by niwsa** [aecostas/huffman#1]
Hi @aecostas I compiled the coffeescript code to js but finding it hard to understand the logic. Is it possible for you to share the algorithm or any helpful links to better understand the code ?

**Comment by aecostas** [comment]
Hi @niwsa , sorry for my late reply. I follow the original Huffman algorithm to obtain a compact code, as described in the book http://www.casadellibro.com/libro-teoria-de-la-informacion-y-codificacion/9788484082200/879106 (in Spanish)

This is and old project. I can recover it a convert to ES6 with more test data
